# Site settings
title: José Juan Sánchez
tagline: PhD. Student in Computer Science
email: josejuan.sanchez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  PhD. Student in Computer Science
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://josejuansanchez.org" # the base hostname & protocol for your site
logourl:  # Site logo
author: "José Juan Sánchez Hernández"
author_thumbnail: "/assets/images/avatar.png" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar
  highlight_color: "#272935" #"#205081"

  # Color for links, etc
  links_highlight_color: "#205081" 

  # Social media links, leave blank to ignore
  social: 
    github: josejuansanchez
    twitter: josejuansanchez
    #facebook: 
    gplus: +josejuansanchezhernandez
    # dribble: 
    pinterest: josejuansanchez

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
